### PR TITLE
Single map mccs function

### PR DESCRIPTION
**Pull request by PierreBarrat**
We had several functions to map nodes of a tree to their MCC: `assign_mccs!`, `mcc_map`, and `leaf_mcc_map`. 
This combines the two in one (+) function: 
- `map_mccs(MCCs)` simply maps the leaves. Returns a `Dict`
- `map_mccs(tree, MCCs; internals=true)` maps all nodes of `tree`. Returns a `Dict`. If `internals=false`, same as above. 
- `map_mccs!(tree::Tree{MiscData}, MCCs; internals=true)` maps all nodes of `tree`. For each node `n` MCC index is stored in `n.data["mcc"]`. The key `n.data["child_mccs"]` is also set. 

All these use the same Fitch algorithm. 

The new function is in `src/mcc_tools.jl`. I removed `src/mcc_branch_length.jl`. The old functions are all removed. 

Passes all test. What do you think?

### CODE REVIEW

**Comment by anna-parker** [comment]
This looks good! We might just want to consider allowing `sort_polytomy_strict!` and `resolve_strict!` to work on all tree types now as this would now be possible as `mcc_map` should be able to map all mccs to trees now - including strictly resolved trees. But we could also do that in another PR and merge this now :-)

**Comment by PierreBarrat** [comment]
I was not sure about this actually: `sort_polytomies!` and `sort_polytomies_strict` do exactly the same thing, except that the first one takes a map as input while the second one expects data to be on the tree? 
Does this mean I can just *remove* `sort_polytomies_strict!` completely since `map_mccs` now works both strictly and non strictly resolved trees?

**Comment by anna-parker** [comment]
Yes - I just tested and it works as it should - will remove `sort_polytomies_strict` now

**Comment by PierreBarrat** [comment]
Nice! All good to merge then?

**Comment by anna-parker** [comment]
Yes :-)

**Pull request merged**
